### ISSUE TITLE
Sparse Retrieval

### ISSUE THREAD

**Issue by tangzhy** [thunlp/OpenMatch#11]
hi，do you support building index for sparse retreival? 

I see you mentioned Anserini. But I see neither examples nor api help us build a bm25 inverted index.

BTW, I'm not used to JAVA, and find Anserini kind of difficult to build a sparse index. Do you have any suggestion for my purpose?

**Comment by zkt12** [comment]
It's very convenient using Anserini for sparse index. We compiled a former version of it, available at https://github.com/thunlp/OpenMatch/tree/master/retrievers

You can preprocess your doc corpus to jsonl format: *{'id': str, 'contents': str}*,
and queries to tsv format: *q_id1 \t q1*
then build index:
```
./bm25_retriever/bin/IndexCollection -collection JsonCollection -input {doc corpus} -index {index to build} -generator LuceneDocumentGenerator -threads 8 -storePositions -storeDocvectors -storeRawDocs >& {log file path}
```
Finally, search relevant docs for your queries:
```
./bm25_retriever/bin/SearchCollection -index {index path} -topicreader TsvString -topics {query tsv file} -bm25 -output {result file}
```

**Comment by tangzhy** [comment]
@zkt12 Thanks for your answer. It's really convenient.

But I'm dealing with chinese corpus. 
Should I apply text segmentation on both doc corpus and queries first? 
I guess after that, the Anserini would take white space, aka, `" "` as default separator, build the inverted index, and search. Am I right?

**Comment by zkt12** [comment]
Here is an issue about 'Chinese index and search' in Anserini: https://github.com/castorini/anserini/pull/804
Then I found that both *IndexCollection* and *SearchCollection* have a 'language' argument, default 'en'. I think you can try it first, set the language argument to 'zh'.

**Comment by tangzhy** [comment]
@zkt12 okay. I'll try that first. thanks~
