### ISSUE TITLE
ContrastQG code

### ISSUE THREAD

**Issue by woshizouguo** [thunlp/OpenMatch#12]
In your paper, you mention using contrastQG/QG to generate label/training data. Could you please share the code or repo link?  I do not see its implementation in your repo. 

Thanks,

**Comment by zkt12** [comment]
Hi,

Thanks for your interests, we are still working on ContrastQG/QG.
The code will be open source around the next month :)

Kaitao

**Comment by EdwardZH** [comment]
Hello, for ContrastQG, you can refer to our paper Meta Adaptive Neural Ranking with Contrastive Synthetic Supervision for more details.

**Comment by EdwardZH** [comment]
These codes will be published after this paper is accepted. You can follow our paper to reimplement your own ContrastQG.

**Comment by woshizouguo** [comment]
Thanks!
