### ISSUE TITLE
what is the parameter score?

### ISSUE THREAD

**Issue by gm0616** [thunlp/OpenMatch#13]
Hi,
After generating the feature of the first passage, I wanna compute the ranking score using the weights as the following script, but encounter the error about *f0.score*, which I can not find any mention.
```shell
java -jar LeToR/RankLib-2.1-patched.jar -load checkpoints/f_maxp.ca -rank features/bert-base_ance_eval_maxp_features -score f0.score
```
> Error in RankerFactory.load(): java.lang.NullPointerException
Traceback (most recent call last):
  File "LeToR/gen_trec.py", line 48, in <module>
    main()
  File "LeToR/gen_trec.py", line 19, in main
    with open('f' + str(args.k+1) + '.score', 'r') as r:
FileNotFoundError: [Errno 2] No such file or directory: 'f0.score'

**Comment by zkt12** [comment]
Hi,
Was the f0.score generated after running this script? This error occurs in running gen_trec.py, which aims to generate TREC format ranking list from f0.score, but the f0.score file is not found.

Kaitao
