### ISSUE TITLE
ANCE firstP and maxP doc ranking leaderboard result reproduce

### ISSUE THREAD

**Issue by jacklin64** [thunlp/OpenMatch#15]
Thanks for your great resource. If I want to reproduce ANCE doc ranking leaderboard result for firstP and maxP (dev set MRR@100 0.373 and 0.383 respectively), should we use the corresponding checkpoints from the ANCE original repo (https://github.com/microsoft/ANCE) ? Or it is another checkpoint from the repo (https://github.com/thunlp/OpenMatch/blob/master/docs/experiments-msmarco-doc.md) although I cannot find the checkpoint there.

**Comment by zkt12** [comment]
We used the checkpoints from the ANCE original repo - **TREC DL Document NDCG@10** :)
