### ISSUE TITLE
bert.py does not accept arguments that should be passed to transformers module

### ISSUE THREAD

**Issue by ali-abz** [thunlp/OpenMatch#16]
Hi there,
I was trying to use a bert-like model as a ranker and got an error raised by transformers module saying that the model is trained on TF and I need to pass some arguments to resolve it. I'm not sure if it's appropriate or not but I think bert.py should pass any other arguments to transformers module.

**Comment by zkt12** [comment]
Hi, this error may be caused by initializing the bert-like model from a checkpoint that saved by TF. Could you show me your scripts or codes?
