### ISSUE TITLE
Cannot Find File queries.train.small.tsv

### ISSUE THREAD

**Issue by VickiCui** [thunlp/OpenMatch#17]
Hi，
I was trying to train a BERT model for MS MARCO Passage Ranking. And according to the bash, there needs a ‘queries.train.small.tsv’ file. But I didn't find any download link on the MS MARCO website. Where can I get this file?
Thanks!

**Comment by zkt12** [comment]
Hi,
You can just change the name of ‘queries.train.tsv’ to ‘queries.train.small.tsv’ or change the path to ‘queries.train.tsv’ file. What we need here is a tsv file that contains all training queries in the ‘trids_bm25_marco-10.tsv’ file :)
Kaitao

**Comment by VickiCui** [comment]
Thanks!
