### ISSUE TITLE
这个msmarco-docs-firstp.tsv 文件是需要自己创建吗？

### ISSUE THREAD

**Issue by xiaoyichao** [thunlp/OpenMatch#18]
这个msmarco-docs-firstp.tsv 文件是需要自己创建吗？

**Comment by zkt12** [comment]
对，我们firstp的做法是把官方给的document集合title和content用空格或[SEP]拼起来，文件的每行整理成docid \t title+content的形式。

**Comment by xiaoyichao** [comment]
> 对，我们firstp的做法是把官方给的document集合title和content用空格或[SEP]拼起来，文件的每行整理成docid \t title+content的形式。

感谢解答！
