### ISSUE TITLE
Why use gumbel softmax before sampling actions?

### ISSUE THREAD

**Issue by KinvenW** [thunlp/OpenMatch#28]
Hi, I want to use OpenMatch to reproduce results of ReinfoSelect, and I found that you add gumbel softmax before sampling step, while in [original code repository](https://github.com/thunlp/ReInfoSelect/blob/6e8e1044e887f07045699fdf5575ddbe4b6979bc/ReInfoSelect/main.py)  of the paper there is no such gumbel softmax. I can't understand the purpose of adding the Gumbel Softmax here, could you explain it to me?

**Comment by EdwardZH** [comment]
Both softmax and gumbel softmax are suitable for reinfoselect. I change the vanilla softmax to gumbel softmax because the probability distribution is smooth. Thus, using gumbel softmax can make the selection probability more shape.
