### ISSUE TITLE
The datasets

### ISSUE THREAD

**Issue by doubleQ2018** [thunlp/OpenMatch#3]
Could you please share the datesets (ClueWeb09, Robust04, and ClueWeb12) in the experiment?

**Comment by zkt12** [comment]
It requires a license to get these datasets. You can visit the following web pages for it:
* http://lemurproject.org/clueweb09/
* http://www.lemurproject.org/clueweb12.php/

Please let me know that you have been permitted to access these datasets. My email address is
* zkt18@mails.tsinghua.edu.cn.

Our results on MS MARCO dataset are coming soon, together with the related data and experimental details.  Are you interested? If so, we'll let you know as soon as they are available.

**Comment by zkt12** [comment]
Our msmarco data and checkpoint are available now, you can try it out :)
