### ISSUE TITLE
how is the file 'run.msmarco-passage.dev.small.trec' generated?

### ISSUE THREAD

**Issue by KinvenW** [thunlp/OpenMatch#36]

**Comment by Yu-Shi** [comment]
Hello, it's generated by Anserini BM25 on msmarco dev queries. You can use Pyserini, a python interface for Anserini.

**Comment by KinvenW** [comment]
> Hello, it's generated by Anserini BM25 on msmarco dev queries. You can use Pyserini, a python interface for Anserini.

Thanks :)
