### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Maheshkumar094** [thunlp/OpenMatch#4]
On executing **sh train_bert.sh**  getting error **Segmentation fault (core dumped)**
Configuration of My VM
RAM - 26 GB
GPU - 2 (Tesla T4 )
Any Comment will be highly appreciated.

**Comment by zkt12** [comment]
Could you please copy the script details here?

**Comment by Maheshkumar094** [comment]
CUDA_VISIBLE_DEVICES=0 \
python train.py \
        -task ranking \
        -model bert \
        -train ./data/train_rank_toy.jsonl \
        -max_input 1280000 \
        -save ./checkpoints/scibert.bin \
        -dev ./data/dev_toy.jsonl \
        -qrels ./data/qrels_toy \
        -vocab allenai/scibert_scivocab_uncased \
        -pretrain allenai/scibert_scivocab_uncased \
        -res ./results/scibert.trec \
        -metric ndcg_cut_10 \
        -max_query_len 32 \
        -max_doc_len 256 \
        -epoch 1 \
        -batch_size 4 \
        -lr 2e-5 \
        -eval_every 1000

**Comment by zkt12** [comment]
I've tested this, and it worked fine.
Could you copy the whole error code, and share the version of python, pytorch and transformers?
The suggested requirements for openmatch is at https://github.com/thunlp/OpenMatch/blob/master/requirements.txt

**Comment by Maheshkumar094** [comment]
@zkt12 
After fresh installation for python requirement, the error is gone
I am able to execute **sh train_bert.sh**  
```
CUDA_VISIBLE_DEVICES=0 \
python train.py \
        -task ranking \
        -model bert \
        -train ./data/train_rank_toy.jsonl \
        -max_input 1280000 \
        -save ./checkpoints/scibert.bin \
        -dev ./data/dev_toy.jsonl \
        -qrels ./data/qrels_toy \
        -vocab allenai/scibert_scivocab_uncased \
        -pretrain allenai/scibert_scivocab_uncased \
        -res ./results/scibert.trec \
        -metric ndcg_cut_10 \
        -max_query_len 32 \
        -max_doc_len 256 \
        -epoch 1 \
        -batch_size 4 \
        -lr 2e-5 \
        -eval_every 1000
```
After complete excution **./checkpoints/scibert.bin** file is not created that way after excution of  **inference_bert.sh** 
```
CUDA_VISIBLE_DEVICES=0 \
python inference.py \
        -task classification \
        -model bert \
        -max_input 1280000 \
        -test ./data/test_toy.jsonl \
        -vocab bert-base-uncased \
        -pretrain bert-base-uncased \
        -checkpoint ./checkpoints/bert.bin \
        -res ./results/bert.trec \
        -max_query_len 32 \
        -max_doc_len 256 \
        -batch_size 32
```
getting error 
```
reading test data...
Traceback (most recent call last):
  File "inference.py", line 200, in <module>
    main()
  File "inference.py", line 176, in main
    state_dict = torch.load(args.checkpoint)
  File "/home/hexaai/InformationRetrival/env/lib/python3.6/site-packages/torch/serialization.py", line 525, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/hexaai/InformationRetrival/env/lib/python3.6/site-packages/torch/serialization.py", line 212, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/hexaai/InformationRetrival/env/lib/python3.6/site-packages/torch/serialization.py", line 193, in __init__
    super(_open_file, self).__init__(open(name, mode))
**FileNotFoundError: [Errno 2] No such file or directory: './checkpoints/bert.bin'**
```


Kindly help me.

**Comment by zkt12** [comment]
*train.sh* set the *eval_every* to 1000, the dev set will be evaluated every 1000 steps, then the best performed model will be saved. But the toy dataset is too small to reach 1000 steps, so there is no model saved.
I've changed the *eval_every* to 10, you can try it out :)

**Comment by zkt12** [comment]
We've shared the checkpoints of models trained on trec-covid and msmarco dataset.
You can preprocess the user topics and articles to format in https://github.com/thunlp/OpenMatch/blob/master/docs/openmatch.md, and inference.

The *inference.py* outputs a file in standard trec format by default, each line is like follows:
```
query_id Q0 doc_id rank score run-tag
```
if you don't want the trec file, we have the *test* function in *inference.py* which outputs a dict:
```
{query1: [(doc1_ranking_score, doc1_id), (doc2_ranking_score, doc2_id), ...], query_2: ...}
```
you can format the output yourself with this.

**Comment by Maheshkumar094** [comment]
Could you please share the entire project description in the readme.md file
It will be helpfull for me to know the actual concept of the project a test it with some other dataset.
Thank You.

**Comment by xiongchenyan** [comment]
I think your question is more in general about IR not about this open source project. As long as you can run the example successfully, I think this issue can be closed.
