### ISSUE TITLE
RankSVM (OpenMatch) Coor-Ascent (OpenMatch) 

### ISSUE THREAD

**Issue by eryihaha** [thunlp/OpenMatch#40]
请问RankSVM (OpenMatch) Coor-Ascent (OpenMatch)  两个模块在哪里实现的呢，代码里没有找到欸

**Comment by EdwardZH** [comment]
这两个部分是整合traditional IR feature时候用的，你可以参考https://github.com/thunlp/OpenMatch/blob/master/OpenMatch/extractors/classic_extractor.py

**Comment by Yu-Shi** [comment]
在这个里面的 java 包
https://github.com/thunlp/OpenMatch/tree/master/LeToR

**Comment by eryihaha** [comment]
好的谢谢！
