### ISSUE TITLE
Where is  dev_trec-covid-round1.jsonl ?

### ISSUE THREAD

**Issue by xiaohong020408** [thunlp/OpenMatch#5]
I want to train,  but I couldn't got a dev_trec-covid-round1.jsonl  file.
Thank you very much.

**Comment by zkt12** [comment]
Hi,
dev_trec-covid-round1.jsonl file can be generated as follows, the trec-covid doc file has been updated:
```
python ./data/preprocess.py \
  -input_trec anserini.covid-r1.fusion1.txt \
  -input_qrels qrels-cord19-round1.txt \
  -input_queries questions_cord19-rnd1.txt \
  -input_docs cord19_0501_titabs.jsonl \
  -output ./data/dev_trec-covid-round1.jsonl
```

**Comment by xiaohong020408** [comment]
I have got it.  Using this command.  

python ./data/preprocess.py \
  -input_trec ./data/covoid/**run.covid-r1.fusion1.txt** \
  -input_qrels ./data/covoid/qrels-cord19-round1.txt \
  -input_queries ./data/covoid/questions_cord19-rnd1.txt \
  -input_docs ./data/covoid/cord19_0501_titabs.jsonl \
  -output ./data/covoid/dev_trec-covid-round1.jsonl

 The file name has changed .

Thank you very much .
