### ISSUE TITLE
How to generate TREC COVID?

### ISSUE THREAD

**Issue by xiaohong020408** [thunlp/OpenMatch#6]
I want to generate TREC COID file, e.g.  run.covid-r1.fusion1.txt, I have tried to run

 ./bm25_retriever/bin/IndexCollection -collection JsonCollection -input {your collection} -index {index path} -generator LuceneDocumentGenerator -threads 8 -storePositions -storeDocvectors -storeRawDocs >& {log file path}
```
Search by BM25:
```
./bm25_retriever/bin/SearchCollection -index {index path} -topicreader {topic format} -topics {topic path} -bm25 -output {result file path}

But there is gap betweendownloaded  dataset e.g.  cord-19_2020-05-01.tar.gz  and index input {your collection}.

Could you help me?  Thanks a lot.

**Comment by zkt12** [comment]
We followed *anserini* to generate these data, here's the links:
* https://github.com/castorini/anserini/blob/master/docs/experiments-cord19.md
* https://github.com/castorini/anserini/blob/master/docs/experiments-covid.md

**Comment by xiaohong020408** [comment]
Thanks a lot.
